### ISSUE TITLE
What and how to use SingleSourceoftruth in case of network call only and no Database.

### ISSUE THREAD

**Issue by mfsi-prateeksharma** [Eli-Fox/LEGO-Catalog#2]
@Eli-Fox , I am having a project in which only network calls are to be made and no use of local DB. So how to follow that approach in this project? How will SingleSourceofTruth file will work?

**Comment by shahzadhemani17** [comment]
Also facing same issue, i will to remove DB but getting stuck in to problems when i try to do so.
`fun <T, A> resultLiveData(
                          networkCall: suspend () -> Result<A>): LiveData<Result<T>> =
        liveData(Dispatchers.IO) {
            emit(Result.loading<T>())

            val responseStatus = networkCall.invoke()

            if (responseStatus.status == Result.Status.SUCCESS) {
                emit(Result.success<T>(responseStatus.data!!))   (facing error here)
            } else if (responseStatus.status == Result.Status.ERROR) {
                emit(Result.error<T>(responseStatus.message!!))
            }
        }`
here i am not able to emit data because its of type A

` val themes = resultLiveData(
        networkCall = { nashmiRemoteDataSource.fetchData() })`

And here i am facing compile time error because of generics

**Comment by fjr619** [comment]
you can revamp into like this

```
fun <T> resultLiveData(networkCall: suspend () -> Result<T>): LiveData<Result<T>> =
    liveData(Dispatchers.IO) {
        emit(Result.loading<T>())
        val responseStatus = networkCall.invoke()
        if (responseStatus.status == SUCCESS) {
            emit(Result.success(responseStatus.data!!))
        } else if (responseStatus.status == ERROR) {
            emit(Result.error<T>(responseStatus.message!!))
        }
    }
```
in my project i didnt have db too, after revamp to that, it will work fine

**Comment by mfsi-prateeksharma** [comment]
This is my version similar to @fjr619 @shahzadhemani17 you can follow anyone. 
```
fun <A> resultLiveData(
                          networkCall: suspend () -> Result<A>
): LiveData<Result<A>> =
        liveData(Dispatchers.IO) {
            emit(Result.Loading())
            val responseStatus = networkCall.invoke()
            if (responseStatus is Result.Success) {
                emit(Result.Success(responseStatus.data))
            } else if (responseStatus is Result.Error) {
                emit(Result.Error(responseStatus.message))
            }
        }
```
**I expect that the data could be null, so I am not asserting it with not null.**
